### ISSUE TITLE
Issue, termux 

### ISSUE THREAD

**Issue by Ptagdam** [rsnlabs/rsnchat-js#8]
node index.js
/storage/emulated/0/test/node_modules/rsnchat/build/cjs/index.cjs:50
                throw new Error(`Invalid API Key (403 Forbidden): ${apikey}`);
                      ^

Error: Invalid API Key (403 Forbidden): rsnai_mFUvwfuRH9b2x4v85lyxJhKU
    at /storage/emulated/0/test/node_modules/rsnchat/build/cjs/index.cjs:50:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.6.2

**Comment by iscordian** [comment]
> node index.js /storage/emulated/0/test/node_modules/rsnchat/build/cjs/index.cjs:50 throw new Error(`Invalid API Key (403 Forbidden): ${apikey}`); ^
> 
> Error: Invalid API Key (403 Forbidden): rsnai_mFUvwfuRH9b2x4v85lyxJhKU at /storage/emulated/0/test/node_modules/rsnchat/build/cjs/index.cjs:50:23 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v21.6.2

Api key is not valid bro

**Comment by Rstacx** [comment]
There is no issue on our side.
Try generating the key again or send me a dm.

**Comment by Ptagdam** [comment]
> There is no issue on our side. Try generating the key again or send me a dm.

how to setup on cpanel

**Comment by Ptagdam** [comment]
> There is no issue on our returncode: 1
stdout:
> @ start /home/pxxxxxb/chat.pxxxxxb.com
> node index.js
stderr:
npm WARN lifecycle The node binary used for scripts is /home/pxxxxx/nodevenv/chat.pukathub.com/10/bin/node but npm is using /opt/alt/alt-nodejs10/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'rsnchat'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/xxxxxxx/chat.pxxxxx.com/index.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxxx/.npm/_logs/2024-04-13T13_08_58_884Z-debug.logside. Try generating the key again or send me a dm.

**Comment by Rstacx** [comment]
> > There is no issue on our returncode: 1
> > stdout:
> > @ start /home/pxxxxxb/chat.pxxxxxb.com
> > node index.js
> > stderr:
> > npm WARN lifecycle The node binary used for scripts is /home/pxxxxx/nodevenv/chat.pukathub.com/10/bin/node but npm is using /opt/alt/alt-nodejs10/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> > internal/modules/cjs/loader.js:638
> > throw err;
> > ^
> 
> Error: Cannot find module 'rsnchat' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) at Function.Module._load (internal/modules/cjs/loader.js:562:25) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object. (/home/xxxxxxx/chat.pxxxxx.com/index.js:2:21) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! @ start: `node index.js` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the @ start script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /home/xxxxx/.npm/_logs/2024-04-13T13_08_58_884Z-debug.logside. Try generating the key again or send me a dm.

`npm i rsnchat@latest`

**Comment by Ptagdam** [comment]
How to run on cpanel
