### ISSUE TITLE
why am i getting an api error?. pls helpp

### ISSUE THREAD

**Issue by Wumpus2000** [rsnlabs/rsnchat-js#9]
``` js
Error fetching data from RSNAI Cartoon API: AxiosError: Request failed with status code 404
    at settle (C:\Users\myhxb\OneDrive\Documents\wampas\node_modules\axios\dist\node\axios.cjs:1966:12)
    at BrotliDecompress.handleStreamEnd (C:\Users\myhxb\OneDrive\Documents\wampas\node_modules\axios\dist\node\axios.cjs:3065:11)
    at BrotliDecompress.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (C:\Users\myhxb\OneDrive\Documents\wampas\node_modules\axios\dist\node\axios.cjs:3876:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (C:\Users\myhxb\OneDrive\Documents\wampas\src\commands\Slash\Fun\prodia.js:46:30) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.6.8',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://api.rsnai.org/api/v1/user/prodia?prompt=a cat&negative_prompt=a dog',      
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.rsnai.org',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.rsnai.org',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      write: [Function: writeAfterFIN],
      [Symbol(res)]: null,
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 1566,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 772,
      [Symbol(kBytesWritten)]: 229,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'GET /api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog HTTP/1.1\r\n' + 
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/1.6.8\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: api.rsnai.org\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.rsnai.org/api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 30,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.rsnai.org',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.rsnai.org/api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: Object [AxiosHeaders] {
      date: 'Wed, 17 Apr 2024 21:50:27 GMT',
      'content-type': 'application/json; charset=utf-8',
      'transfer-encoding': 'chunked',
      connection: 'close',
      'x-powered-by': 'Express',
      etag: 'W/"35-Mw9GG6sD8SclD6uDgThfKyTEjos"',
      'x-do-app-origin': '98ee8acd-5a0e-41ec-9ad7-b45b7970d74a',
      'cache-control': 'private',
      'x-do-orig-status': '404',
      'cf-cache-status': 'MISS',
      'set-cookie': [Array],
      vary: 'Accept-Encoding',
      server: 'cloudflare',
      'cf-ray': '875fa1761fad8432-YVR'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'get',
      url: 'https://api.rsnai.org/api/v1/user/prodia?prompt=a cat&negative_prompt=a dog',    
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'GET /api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.6.8\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: api.rsnai.org\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.rsnai.org',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { success: false, message: 'Organization not found.' }
  }
}
```
![image](https://github.com/rsnlabs/rsnchat-js/assets/66653764/f35d88a5-1220-4c69-847c-b4e20c70d1d6)

**Comment by Rstacx** [comment]
> ```js
> Error fetching data from RSNAI Cartoon API: AxiosError: Request failed with status code 404
>     at settle (C:\Users\myhxb\OneDrive\Documents\wampas\node_modules\axios\dist\node\axios.cjs:1966:12)
>     at BrotliDecompress.handleStreamEnd (C:\Users\myhxb\OneDrive\Documents\wampas\node_modules\axios\dist\node\axios.cjs:3065:11)
>     at BrotliDecompress.emit (node:events:526:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
>     at Axios.request (C:\Users\myhxb\OneDrive\Documents\wampas\node_modules\axios\dist\node\axios.cjs:3876:41)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Object.run (C:\Users\myhxb\OneDrive\Documents\wampas\src\commands\Slash\Fun\prodia.js:46:30) {
>   code: 'ERR_BAD_REQUEST',
>   config: {
>     transitional: {
>       silentJSONParsing: true,
>       forcedJSONParsing: true,
>       clarifyTimeoutError: false
>     },
>     adapter: [ 'xhr', 'http' ],
>     transformRequest: [ [Function: transformRequest] ],
>     transformResponse: [ [Function: transformResponse] ],
>     timeout: 0,
>     xsrfCookieName: 'XSRF-TOKEN',
>     xsrfHeaderName: 'X-XSRF-TOKEN',
>     maxContentLength: -1,
>     maxBodyLength: -1,
>     env: { FormData: [Function], Blob: [class Blob] },
>     validateStatus: [Function: validateStatus],
>     headers: Object [AxiosHeaders] {
>       Accept: 'application/json, text/plain, */*',
>       'Content-Type': undefined,
>       'User-Agent': 'axios/1.6.8',
>       'Accept-Encoding': 'gzip, compress, deflate, br'
>     },
>     method: 'get',
>     url: 'https://api.rsnai.org/api/v1/user/prodia?prompt=a cat&negative_prompt=a dog',      
>     data: undefined
>   },
>   request: <ref *1> ClientRequest {
>     _events: [Object: null prototype] {
>       abort: [Function (anonymous)],
>       aborted: [Function (anonymous)],
>       connect: [Function (anonymous)],
>       error: [Function (anonymous)],
>       socket: [Function (anonymous)],
>       timeout: [Function (anonymous)],
>       finish: [Function: requestOnFinish]
>     },
>     _eventsCount: 7,
>     _maxListeners: undefined,
>     outputData: [],
>     outputSize: 0,
>     writable: true,
>     destroyed: true,
>     _last: true,
>     chunkedEncoding: false,
>     shouldKeepAlive: false,
>     maxRequestsOnConnectionReached: false,
>     _defaultKeepAlive: true,
>     useChunkedEncodingByDefault: false,
>     sendDate: false,
>     _removedConnection: false,
>     _removedContLen: false,
>     _removedTE: false,
>     strictContentLength: false,
>     _contentLength: 0,
>     _hasBody: true,
>     _trailer: '',
>     finished: true,
>     _headerSent: true,
>     _closed: true,
>     socket: TLSSocket {
>       _tlsOptions: [Object],
>       _secureEstablished: true,
>       _securePending: false,
>       _newSessionPending: false,
>       _controlReleased: true,
>       secureConnecting: false,
>       _SNICallback: null,
>       servername: 'api.rsnai.org',
>       alpnProtocol: false,
>       authorized: true,
>       authorizationError: null,
>       encrypted: true,
>       _events: [Object: null prototype],
>       _eventsCount: 9,
>       connecting: false,
>       _hadError: false,
>       _parent: null,
>       _host: 'api.rsnai.org',
>       _closeAfterHandlingError: false,
>       _readableState: [ReadableState],
>       _maxListeners: undefined,
>       _writableState: [WritableState],
>       allowHalfOpen: false,
>       _sockname: null,
>       _pendingData: null,
>       _pendingEncoding: '',
>       server: undefined,
>       _server: null,
>       ssl: null,
>       _requestCert: true,
>       _rejectUnauthorized: true,
>       parser: null,
>       _httpMessage: [Circular *1],
>       write: [Function: writeAfterFIN],
>       [Symbol(res)]: null,
>       [Symbol(verified)]: true,
>       [Symbol(pendingSession)]: null,
>       [Symbol(async_id_symbol)]: 1566,
>       [Symbol(kHandle)]: null,
>       [Symbol(lastWriteQueueSize)]: 0,
>       [Symbol(timeout)]: null,
>       [Symbol(kBuffer)]: null,
>       [Symbol(kBufferCb)]: null,
>       [Symbol(kBufferGen)]: null,
>       [Symbol(kCapture)]: false,
>       [Symbol(kSetNoDelay)]: false,
>       [Symbol(kSetKeepAlive)]: true,
>       [Symbol(kSetKeepAliveInitialDelay)]: 60,
>       [Symbol(kBytesRead)]: 772,
>       [Symbol(kBytesWritten)]: 229,
>       [Symbol(connect-options)]: [Object]
>     },
>     _header: 'GET /api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog HTTP/1.1\r\n' + 
>       'Accept: application/json, text/plain, */*\r\n' +
>       'User-Agent: axios/1.6.8\r\n' +
>       'Accept-Encoding: gzip, compress, deflate, br\r\n' +
>       'Host: api.rsnai.org\r\n' +
>       'Connection: close\r\n' +
>       '\r\n',
>     _keepAliveTimeout: 0,
>     _onPendingData: [Function: nop],
>     agent: Agent {
>       _events: [Object: null prototype],
>       _eventsCount: 2,
>       _maxListeners: undefined,
>       defaultPort: 443,
>       protocol: 'https:',
>       options: [Object: null prototype],
>       requests: [Object: null prototype] {},
>       sockets: [Object: null prototype] {},
>       freeSockets: [Object: null prototype] {},
>       keepAliveMsecs: 1000,
>       keepAlive: false,
>       maxSockets: Infinity,
>       maxFreeSockets: 256,
>       scheduling: 'lifo',
>       maxTotalSockets: Infinity,
>       totalSocketCount: 0,
>       maxCachedSessions: 100,
>       _sessionCache: [Object],
>       [Symbol(kCapture)]: false
>     },
>     socketPath: undefined,
>     method: 'GET',
>     maxHeaderSize: undefined,
>     insecureHTTPParser: undefined,
>     joinDuplicateHeaders: undefined,
>     path: '/api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog',
>     _ended: true,
>     res: IncomingMessage {
>       _readableState: [ReadableState],
>       _events: [Object: null prototype],
>       _eventsCount: 4,
>       _maxListeners: undefined,
>       socket: [TLSSocket],
>       httpVersionMajor: 1,
>       httpVersionMinor: 1,
>       httpVersion: '1.1',
>       complete: true,
>       rawHeaders: [Array],
>       rawTrailers: [],
>       joinDuplicateHeaders: undefined,
>       aborted: false,
>       upgrade: false,
>       url: '',
>       method: null,
>       statusCode: 404,
>       statusMessage: 'Not Found',
>       client: [TLSSocket],
>       _consuming: true,
>       _dumped: false,
>       req: [Circular *1],
>       responseUrl: 'https://api.rsnai.org/api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog',
>       redirects: [],
>       [Symbol(kCapture)]: false,
>       [Symbol(kHeaders)]: [Object],
>       [Symbol(kHeadersCount)]: 30,
>       [Symbol(kTrailers)]: null,
>       [Symbol(kTrailersCount)]: 0
>     },
>     aborted: false,
>     timeoutCb: null,
>     upgradeOrConnect: false,
>     parser: null,
>     maxHeadersCount: null,
>     reusedSocket: false,
>     host: 'api.rsnai.org',
>     protocol: 'https:',
>     _redirectable: Writable {
>       _writableState: [WritableState],
>       _events: [Object: null prototype],
>       _eventsCount: 3,
>       _maxListeners: undefined,
>       _options: [Object],
>       _ended: true,
>       _ending: true,
>       _redirectCount: 0,
>       _redirects: [],
>       _requestBodyLength: 0,
>       _requestBodyBuffers: [],
>       _onNativeResponse: [Function (anonymous)],
>       _currentRequest: [Circular *1],
>       _currentUrl: 'https://api.rsnai.org/api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog',
>       [Symbol(kCapture)]: false
>     },
>     [Symbol(kCapture)]: false,
>     [Symbol(kBytesWritten)]: 0,
>     [Symbol(kNeedDrain)]: false,
>     [Symbol(corked)]: 0,
>     [Symbol(kOutHeaders)]: [Object: null prototype] {
>       accept: [Array],
>       'user-agent': [Array],
>       'accept-encoding': [Array],
>       host: [Array]
>     },
>     [Symbol(errored)]: null,
>     [Symbol(kHighWaterMark)]: 16384,
>     [Symbol(kRejectNonStandardBodyWrites)]: false,
>     [Symbol(kUniqueHeaders)]: null
>   },
>   response: {
>     status: 404,
>     statusText: 'Not Found',
>     headers: Object [AxiosHeaders] {
>       date: 'Wed, 17 Apr 2024 21:50:27 GMT',
>       'content-type': 'application/json; charset=utf-8',
>       'transfer-encoding': 'chunked',
>       connection: 'close',
>       'x-powered-by': 'Express',
>       etag: 'W/"35-Mw9GG6sD8SclD6uDgThfKyTEjos"',
>       'x-do-app-origin': '98ee8acd-5a0e-41ec-9ad7-b45b7970d74a',
>       'cache-control': 'private',
>       'x-do-orig-status': '404',
>       'cf-cache-status': 'MISS',
>       'set-cookie': [Array],
>       vary: 'Accept-Encoding',
>       server: 'cloudflare',
>       'cf-ray': '875fa1761fad8432-YVR'
>     },
>     config: {
>       transitional: [Object],
>       adapter: [Array],
>       transformRequest: [Array],
>       transformResponse: [Array],
>       timeout: 0,
>       xsrfCookieName: 'XSRF-TOKEN',
>       xsrfHeaderName: 'X-XSRF-TOKEN',
>       maxContentLength: -1,
>       maxBodyLength: -1,
>       env: [Object],
>       validateStatus: [Function: validateStatus],
>       headers: [Object [AxiosHeaders]],
>       method: 'get',
>       url: 'https://api.rsnai.org/api/v1/user/prodia?prompt=a cat&negative_prompt=a dog',    
>       data: undefined
>     },
>     request: <ref *1> ClientRequest {
>       _events: [Object: null prototype],
>       _eventsCount: 7,
>       _maxListeners: undefined,
>       outputData: [],
>       outputSize: 0,
>       writable: true,
>       destroyed: true,
>       _last: true,
>       chunkedEncoding: false,
>       shouldKeepAlive: false,
>       maxRequestsOnConnectionReached: false,
>       _defaultKeepAlive: true,
>       useChunkedEncodingByDefault: false,
>       sendDate: false,
>       _removedConnection: false,
>       _removedContLen: false,
>       _removedTE: false,
>       strictContentLength: false,
>       _contentLength: 0,
>       _hasBody: true,
>       _trailer: '',
>       finished: true,
>       _headerSent: true,
>       _closed: true,
>       socket: [TLSSocket],
>       _header: 'GET /api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog HTTP/1.1\r\n' +
>         'Accept: application/json, text/plain, */*\r\n' +
>         'User-Agent: axios/1.6.8\r\n' +
>         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
>         'Host: api.rsnai.org\r\n' +
>         'Connection: close\r\n' +
>         '\r\n',
>       _keepAliveTimeout: 0,
>       _onPendingData: [Function: nop],
>       agent: [Agent],
>       socketPath: undefined,
>       method: 'GET',
>       maxHeaderSize: undefined,
>       insecureHTTPParser: undefined,
>       joinDuplicateHeaders: undefined,
>       path: '/api/v1/user/prodia?prompt=a%20cat&negative_prompt=a%20dog',
>       _ended: true,
>       res: [IncomingMessage],
>       aborted: false,
>       timeoutCb: null,
>       upgradeOrConnect: false,
>       parser: null,
>       maxHeadersCount: null,
>       reusedSocket: false,
>       host: 'api.rsnai.org',
>       protocol: 'https:',
>       _redirectable: [Writable],
>       [Symbol(kCapture)]: false,
>       [Symbol(kBytesWritten)]: 0,
>       [Symbol(kNeedDrain)]: false,
>       [Symbol(corked)]: 0,
>       [Symbol(kOutHeaders)]: [Object: null prototype],
>       [Symbol(errored)]: null,
>       [Symbol(kHighWaterMark)]: 16384,
>       [Symbol(kRejectNonStandardBodyWrites)]: false,
>       [Symbol(kUniqueHeaders)]: null
>     },
>     data: { success: false, message: 'Organization not found.' }
>   }
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/66653764/323388658-f35d88a5-1220-4c69-847c-b4e20c70d1d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjAxNTcsIm5iZiI6MTcxMzQxOTg1NywicGF0aCI6Ii82NjY1Mzc2NC8zMjMzODg2NTgtZjM1ZDg4YTUtMTIyMC00YzY5LTg0N2MtYjRlMjBjNzBkMWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA1NTczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljZjY3NjFlZjc2ZmFmYzQ5NmU4NzAxMjM1ZDg5ZGQ2NzYwYzNhODYwMzY1MDM3NGU0YWY4Nzg3MDdiNzJkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M0QFkkSw62__9tbEYdinhnETDYVGcy9wgM_zs3rIUq0)

The post method is not a get method

**Comment by Wumpus2000** [comment]
is there an example of get method?

**Comment by Rstacx** [comment]
> is there an example of get method?

The get method does not support RsnAPI. Try the post method 
I checked and there is no such issue
